name: Build

on: [push, workflow_dispatch]

jobs:

  build-on-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Configure and build
        run: |
          cmake . -B build -A x64
          cmake --build build --config Release

      - name: test
        run: |
          cd test
          ctest -C Release --output-on-failure